test : Welcome Spring Boot
spring :
    profiles :
      active : dev
    #默认数据库配置
    datasource:
        url : jdbc:mysql://172.20.135.19:3306/user_tag?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;
        username  : root
        password : gggggg
        driverClassName : com.mysql.jdbc.Driver
    #mongodb配置
#    mongodb:
#        ip : 172.20.135.19
#        port : 27017
#        dbname : user_tag
    data :
        mongodb :
          host : 172.20.135.19
          port : 27017
          database : user_tag
    #freemarker配置
    freemarker:
        checkTemplateLocation : false
        cache: false
        templateLoaderPath : classpath:/view/
        setting :
          template_update_delay : 0
          default_encoding : UTF-8

server :
  port : 3500
  session-timeout : 3600

---
#开发环境配置
spring :
  profiles : dev

name : Dev

---
#生产环境配置
spring :
  profiles : master
  datasource:
          url : jdbc:mysql://121.199.45.45:3306/statistics?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;
          username  : root
          password : sky_log@123ss
          driverClassName : com.mysql.jdbc.Driver

name : Master

server :
  port : 3600